export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const CURRENT_USER="CURRENT_USER"
export const ERRO_AUTH ='ERROR_AUTH'
export const UPLOAD_PICTURE= "UPLOAD_PICTURE"
export const UPLOAD_BIO= "UPLOAD_BIO"


export const CURRENT_CONVER= "CURRENT_CONVER"

export const GET_ALL_USERS="GET_ALL_USER"

export const LIKE_POST="LIKE_POST"
export const UNLIKE_POST="UNLIKE_POST"
export const GET_POSTS="GET_POSTS"
export const MODIFY_POST="MODIFY_POST"
export const CREATE_COMMENT="CREATE_COMMENT"


export const IS_ROOM_HOST= "IS_ROOM_HOST"
export const CONNECT_ONLY_AUDIO= "CONNECT_ONLY_AUDIO"
export const GET_ROOM_ID= "GET_ROOM_ID"
export const SAVE_INDENTITY= "SAVE_INDENTITY"
export const SHOW_OVERLAY= "SHOW_OVERLAY"
export const SET_PARTICIPANTS = "SET_PARTICIPANTS"







